### ISSUE TITLE
Cannot run demo because of D3 dispatch error

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/lineup.js#185]
The demo running for the first time is getting error as below.
```
Uncaught TypeError: Cannot read property 'on' of undefined
    at d3_dispatch.on (http://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js:492:77)
    at LocalDataProvider.AEventDispatcher.on (http://localhost:63342/lineup.js/dist/LineUpJS.js:156:32)
    at new LineUp (http://localhost:63342/lineup.js/dist/LineUpJS.js:4749:19)
    at Object.create (http://localhost:63342/lineup.js/dist/LineUpJS.js:10002:12)
    at window.onload (http://localhost:63342/lineup.js/demo/test.js:86:23)
```

**Comment by bikramkawan** [comment]
Local problem. Fixed by fresh clone of whole lineup repo after deleting files from local.
